/// Flutter icons MyDoodleIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyDoodleIcons
///      fonts:
///       - asset: fonts/MyDoodleIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyDoodleIcons {
  MyDoodleIcons._();

  static const _kFontFam = 'MyDoodleIcons';
  static const String? _kFontPkg = null;

  static const IconData plus = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData erledigt_stamp = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
