/// Flutter icons MyDoodleIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyDoodleIcons
///      fonts:
///       - asset: fonts/MyDoodleIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyDoodleIcons {
  MyDoodleIcons._();

  static const _kFontFam = 'MyDoodleIcons';
  static const String? _kFontPkg = null;

  static const IconData flowers = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData robot = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tool = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shower = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whisk = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulb = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shirt = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clean = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData welding = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scooter = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
